### ISSUE TITLE
Parameters order of argon2id are not "standard" and cause password not match with other tools

### ISSUE THREAD

**Issue by Benjamin-htr** [adonisjs/hash#12]
### Package version

@adonisjs/hash: 9.0.4 | @adonisjs/core: 6.12.1

### Describe the bug

Hi !

For a bit of context, passwords in my database are historically hashed via a legacy symfony api configured to use argon2id. Symfony uses libsodium under the hood, which implements the argond2id hash algo. 

I'm migrating to adonis having configured the password hashes to use the same algorithm and parameters (with lib argon2 version 0.41.1). This allows my Adonis API to authenticate users on its own side. Verification of existing passwords works well on the Adonis side. The problem is actually with the hash serialization of new passwords on the adonisjs side. The parameters v, m, t and p are not in the right order. Here are a few examples (these are demo passwords):

adonisjs hash for password : test-124_arg
```js
$argon2id$v=19$t=4,m=65536,p=1$oNZeAqWynNAkeJUGcuNMSw$O47kb/ayyV1VWoQLDpI/IkDOYUCF/Ctqzxys4cyEeGc
```

We can see that the parameters are in this order: v -> t -> m -> p

This causes compatibility problems with other tools like this website (for which the password does not match the hash in question) https://argon2.online/ or in my case the symfony hash system wich is not able to match the password and the new adonisjs hash. And if we check on https://github.com/P-H-C/phc-string-format/blob/master/phc-sf-spec.md , we can see "The parameters shall appear in the m,t,p,keyid,data order.", so I assume the adonisjs serialization procees of parameters is not the standard way.

So I dug a little deeper, initially thinking that the problem was with the argon2 library, but that's not the case. In fact, argon2 creates the hash with the parameters in the classic order: v -> m -> t -> p

Here's an example with the following password : test-124_arg
```js
$argon2id$v=19$m=65536,t=3,p=4$UEAvSO0hYPAHtJGUvZCRMg$9pIWVHqz9Se/abTV/RrSqUOhvUZqJbpgbx89BzMMbak
```

The problem comes from the hash serialization performed by adonisjs/hash. It should be noted that correcting this problem would not cause any breaking change in my opinion (because adonisjs is able to match hashes to passwords regardless of the order of the hash parameters).

Thank you for reading. I hope I was clear enough in my description of the problem.

**Comment by Benjamin-htr** [comment]
To make things clearer, here's the problem in pictures : 
- adonisjs hash.make(password) result with password = test-124_arg : 
```js
$argon2id$v=19$t=4,m=65536,p=1$oNZeAqWynNAkeJUGcuNMSw$O47kb/ayyV1VWoQLDpI/IkDOYUCF/Ctqzxys4cyEeGc
```
- verifying hash with password on https://argon2.online/ website (it's the same for legacy symfony api in my case). it not work
![image](https://github.com/user-attachments/assets/b0a84578-3641-4164-82a9-b04c0bb47382)

- if I only swipe t and m parameters manually : 
```js
$argon2id$v=19$m=65536,t=4,p=1$oNZeAqWynNAkeJUGcuNMSw$O47kb/ayyV1VWoQLDpI/IkDOYUCF/Ctqzxys4cyEeGc
```
- verifying hash with password on https://argon2.online/ website (it's the same for legacy symfony api in my case). it work
![image](https://github.com/user-attachments/assets/302f2364-762e-4ab9-b518-b20a784b643d)


- raw argon2 lib argon2.hash(password) result with password = test-124_arg
```js
$argon2id$v=19$m=65536,t=3,p=4$UEAvSO0hYPAHtJGUvZCRMg$9pIWVHqz9Se/abTV/RrSqUOhvUZqJbpgbx89BzMMbak
```
- verifying hash with password on https://argon2.online/ website (it's the same for legacy symfony api in my case). it work

![image](https://github.com/user-attachments/assets/426c2c1b-2bda-4cee-8135-c526c70d4ce7)

**Comment by RomainLanz** [comment]
Closing in favor of the PR.
