### ISSUE TITLE
Deps not included?

### ISSUE THREAD

**Issue by bitkidd** [adonisjs/hash#2]
Shouldn't deps like `phc-argon2`, `phc-bcrypt` and etc be included in main deps, not in devDeps?
I just got a weird issue when could not validate password because `phc-bcrypt` module could not be found.

## Package version
5.0.0

## Node.js and npm version
12.16.3

**Comment by thetutlage** [comment]
Nope. If you are using `argon2`, then why there should be package installed for `bcrypt` and vice-versa.  It is similar to the way Lucid works. You install database driver yourself

**Comment by bitkidd** [comment]
Got it, thank you!
